// Norwegian Power Network Data

export const clusterColors: Record<string, string> = {
  kapital: "#c4a35a",
  media: "#8b4513",
  stat: "#2f4f4f",
  interesseorg: "#704214",
  tankesmie: "#8b0000",
  profesjonell: "#4a4a4a",
  tech: "#1a365d",
  foreign: "#666",
}

export const clusterPositions: Record<string, { x: number; y: number; label: string }> = {
  kapital: { x: 15, y: 35, label: "Kapital" },
  media: { x: 50, y: 15, label: "Media" },
  stat: { x: 85, y: 35, label: "Stat" },
  interesseorg: { x: 25, y: 70, label: "Interesseorg." },
  tankesmie: { x: 50, y: 85, label: "Tankesmier" },
  profesjonell: { x: 75, y: 70, label: "Prof. tenester" },
  tech: { x: 50, y: 50, label: "Tech" },
}

export const powerData = {
  kingmakers: [
    {
      id: "rokke",
      name: "Kjell Inge Røkke",
      role: "Industriarkitekten",
      type: "person",
      cluster: "kapital",
      networth: "42 mrd NOK",
      networthYear: "2024",
      desc: "Kontrollerer 68,2% av Aker ASA gjennom TRG Holding. Styremedlem i fleire Aker-selskap. Bur i Sveits.",
      connections: ["aker", "akerbp", "cognite", "nho"],
    },
    {
      id: "fredriksen",
      name: "John Fredriksen",
      role: "Skipskongen",
      type: "person",
      cluster: "kapital",
      networth: "262 mrd NOK",
      networthYear: "2024",
      desc: "Noregs rikaste. Kontrollerer Frontline, Golden Ocean, Mowi gjennom Hemen Holdings. Bur på Kypros.",
      connections: ["frontline", "mowi", "golden-ocean"],
    },
    {
      id: "witzoe",
      name: "Gustav Witzøe",
      role: "Laksemilliardæren",
      type: "person",
      cluster: "kapital",
      networth: "72 mrd NOK",
      networthYear: "2024",
      desc: "Kontrollerer SalMar gjennom Kvarv AS. Son Gustav Magnar er ein av verdas yngste milliardærar.",
      connections: ["salmar", "kvarv"],
    },
    {
      id: "reitan",
      name: "Odd Reitan",
      role: "Daglegvarekongen",
      type: "person",
      cluster: "kapital",
      networth: "55 mrd NOK",
      networthYear: "2024",
      desc: "Eig 100% av Reitan AS (REMA 1000, 7-Eleven). 24% av norsk daglegvaremarknad.",
      connections: ["rema", "reitan-convenience"],
    },
    {
      id: "hagen",
      name: "Stein Erik Hagen",
      role: "Orkla-grunnaren",
      type: "person",
      cluster: "kapital",
      networth: "35 mrd NOK",
      networthYear: "2024",
      desc: "Kontrollerer Orkla gjennom Canica. Medstiftar av Civita. Borna eig no 30% kvar.",
      connections: ["orkla", "canica", "civita"],
    },
    {
      id: "andresen",
      name: "Johan H. Andresen",
      role: "Den etiske kapitalisten",
      type: "person",
      cluster: "kapital",
      networth: "45 mrd NOK",
      networthYear: "2024",
      desc: "Leiar Ferd. Samstundes leiar for Etikkrådet i Oljefondet - avgjer kva fond kan investere i.",
      connections: ["ferd", "etikkradet", "nbim"],
    },
    {
      id: "stavrum",
      name: "Kjersti Løken Stavrum",
      role: "Medievokteren",
      type: "person",
      cluster: "media",
      networth: null,
      controlsValue: "~50 mrd NOK",
      desc: "CEO Tinius-stiftelsen OG Blommenholm. Styreleiar Schibsted Media. Kontrollerer VG, Aftenposten.",
      connections: ["tinius", "blommenholm", "schibsted"],
    },
  ],

  companies: [
    { id: "aker", name: "Aker ASA", type: "company", cluster: "kapital", connections: ["rokke", "akerbp", "cognite"] },
    { id: "akerbp", name: "Aker BP", type: "company", cluster: "kapital", connections: ["aker", "equinor"] },
    { id: "cognite", name: "Cognite", type: "company", cluster: "tech", connections: ["aker", "microsoft"] },
    { id: "equinor", name: "Equinor", type: "company", cluster: "stat", connections: ["nfd", "akerbp"] },
    { id: "telenor", name: "Telenor", type: "company", cluster: "stat", connections: ["nfd", "space-norway"] },
    { id: "dnb", name: "DNB", type: "company", cluster: "stat", connections: ["nfd", "sparebankstiftelsen"] },
    {
      id: "schibsted",
      name: "Schibsted",
      type: "company",
      cluster: "media",
      connections: ["tinius", "blommenholm", "stavrum"],
    },
    {
      id: "amedia",
      name: "Amedia",
      type: "company",
      cluster: "media",
      connections: ["amediastiftelsen", "sparebankstiftelsen"],
    },
    { id: "tv2", name: "TV2", type: "company", cluster: "media", connections: ["egmont"] },
    { id: "nrk", name: "NRK", type: "company", cluster: "stat", connections: ["kulturdept"] },
    { id: "visma", name: "Visma", type: "company", cluster: "tech", connections: ["hg-capital", "digdir"] },
    { id: "tietoevry", name: "TietoEVRY", type: "company", cluster: "tech", connections: ["digdir", "equinor"] },
    { id: "salmar", name: "SalMar", type: "company", cluster: "kapital", connections: ["witzoe", "kvarv"] },
    { id: "orkla", name: "Orkla", type: "company", cluster: "kapital", connections: ["hagen", "canica"] },
    { id: "rema", name: "REMA 1000", type: "company", cluster: "kapital", connections: ["reitan"] },
    { id: "ferd", name: "Ferd", type: "company", cluster: "kapital", connections: ["andresen", "elopak"] },
    { id: "mowi", name: "Mowi", type: "company", cluster: "kapital", connections: ["fredriksen"] },
    { id: "frontline", name: "Frontline", type: "company", cluster: "kapital", connections: ["fredriksen"] },
  ],

  state: [
    {
      id: "nfd",
      name: "Nærings­departementet",
      type: "state",
      cluster: "stat",
      desc: "Kontrollerer 68 statseigde selskap inkl. Equinor, Telenor, DNB, Norsk Hydro.",
      connections: ["equinor", "telenor", "dnb", "norsk-hydro"],
    },
    {
      id: "nbim",
      name: "Oljefondet (NBIM)",
      type: "state",
      cluster: "stat",
      desc: "Verdas største statsfond. $1.6 billionar. Stemmer i 8800+ selskap globalt.",
      connections: ["etikkradet", "tangen", "finansdept"],
    },
    { id: "digdir", name: "Digdir", type: "state", cluster: "stat", connections: ["visma", "tietoevry", "microsoft"] },
    {
      id: "finansdept",
      name: "Finans­departementet",
      type: "state",
      cluster: "stat",
      connections: ["nbim", "skatteetaten"],
    },
    {
      id: "kulturdept",
      name: "Kultur­departementet",
      type: "state",
      cluster: "stat",
      connections: ["nrk", "medietilsynet"],
    },
  ],

  orgs: [
    {
      id: "nho",
      name: "NHO",
      type: "org",
      cluster: "interesseorg",
      desc: "Næringslivets hovudorganisasjon. 33 000 medlemsbedrifter. Direkte tilgang til regjering.",
      connections: ["civita", "hauglie", "almlid"],
    },
    {
      id: "lo",
      name: "LO",
      type: "org",
      cluster: "interesseorg",
      desc: "Landsorganisasjonen. Historisk finansiert Ap. Eig majoriteten av Agenda.",
      connections: ["agenda", "ap", "fafo"],
    },
    {
      id: "bondelaget",
      name: "Norges Bondelag",
      type: "org",
      cluster: "interesseorg",
      desc: "Forhandlar jordbruksoppgjeret direkte med staten. Grunnla Senterpartiet.",
      connections: ["sp", "landbruksdept"],
    },
    {
      id: "civita",
      name: "Civita",
      type: "org",
      cluster: "tankesmie",
      desc: "Leia av tidl. statsråd Kristin Clemet. Grunnlagt av NHO, Rederiforbundet, Stein Erik Hagen.",
      connections: ["clemet", "nho", "hagen", "hoyre"],
    },
    {
      id: "agenda",
      name: "Agenda",
      type: "org",
      cluster: "tankesmie",
      desc: "Eigd av LO. Raymond Johansen (Oslo-ordførar) er styreleiar.",
      connections: ["lo", "johansen", "ap"],
    },
    {
      id: "tinius",
      name: "Tinius-stiftelsen",
      type: "org",
      cluster: "media",
      desc: "Eig Blommenholm som eig 100% av Schibsted Media og 33% av Polaris.",
      connections: ["stavrum", "blommenholm", "schibsted", "polaris"],
    },
    {
      id: "sparebankstiftelsen",
      name: "Sparebankstiftelsen DNB",
      type: "org",
      cluster: "media",
      desc: "Eig Amediastiftelsen (100% av Amedia) og ~8% av DNB. Kopling bank-media.",
      connections: ["amediastiftelsen", "amedia", "dnb"],
    },
  ],

  professionals: [
    {
      id: "first-house",
      name: "First House",
      type: "pr",
      cluster: "profesjonell",
      desc: "Noregs mektigaste PR-byrå. Stifta av tidl. statsrådar. Koplar næringsliv til politikk.",
      connections: ["hanssen", "listhaug", "hoiby"],
    },
    {
      id: "gk",
      name: "Geelmuyden Kiese",
      type: "pr",
      cluster: "profesjonell",
      desc: "Største nordiske PR-byrå. ~150 tilsette.",
      connections: [],
    },
    {
      id: "bahr",
      name: "BAHR",
      type: "law",
      cluster: "profesjonell",
      desc: "Toppadvokatfirma. Handterer dei største transaksjonane.",
      connections: ["dnb-markets", "equinor"],
    },
    { id: "thommessen", name: "Thommessen", type: "law", cluster: "profesjonell", connections: [] },
    {
      id: "dnb-markets",
      name: "DNB Markets",
      type: "finance",
      cluster: "profesjonell",
      desc: "Nordens største investeringsbank. Sentral i alle store transaksjonar.",
      connections: ["dnb", "bahr"],
    },
    { id: "pareto", name: "Pareto Securities", type: "finance", cluster: "profesjonell", connections: [] },
  ],

  revolvingDoor: [
    {
      id: "hauglie",
      name: "Anniken Hauglie",
      from: "Arbeidsminister",
      fromType: "stat",
      to: "NHO",
      toType: "org",
      desc: "Arbeidsminister 2015-2020 → CEO Norsk olje og gass → Viseadm.dir. NHO",
      year: "2020",
    },
    {
      id: "hanssen",
      name: "Bjarne H. Hanssen",
      from: "Helseminister",
      fromType: "stat",
      to: "First House",
      toType: "pr",
      desc: "Minister i tre departement → Medstiftar First House 2010",
      year: "2010",
    },
    {
      id: "listhaug",
      name: "Sylvi Listhaug",
      from: "First House",
      fromType: "pr",
      to: "FrP-minister",
      toType: "stat",
      desc: "First House-konsulent → Landbruksminister → Innvandringsminister",
      year: "2013",
    },
    {
      id: "clemet",
      name: "Kristin Clemet",
      from: "Utdanningsminister",
      fromType: "stat",
      to: "Civita",
      toType: "tankesmie",
      desc: "Utdanningsminister 2001-2005 → Leiar Civita sidan 2006",
      year: "2006",
    },
    {
      id: "berg-hansen",
      name: "Lisbeth Berg-Hansen",
      from: "NHO",
      fromType: "org",
      to: "Fiskeriminister",
      toType: "stat",
      desc: "NHO-nestleiar → Fiskeriminister → Fleire styre",
      year: "2009",
    },
  ],

  foreign: [
    {
      id: "microsoft",
      name: "Microsoft",
      type: "foreign",
      cluster: "tech",
      desc: "Einaste hyperscaler med norske skysoner. Avtalar med Equinor, DNB, Lånekassen.",
      connections: ["digdir", "equinor", "cognite"],
    },
    {
      id: "hg-capital",
      name: "Hg Capital",
      type: "foreign",
      cluster: "kapital",
      desc: "Britisk PE-fond. Eig 70% av Visma (€19 mrd verdi).",
      connections: ["visma"],
    },
    {
      id: "egmont",
      name: "Egmont",
      type: "foreign",
      cluster: "media",
      desc: "Dansk mediekonsern. Eig 100% av TV2 (7,3 mrd NOK omsetning).",
      connections: ["tv2"],
    },
    {
      id: "azrieli",
      name: "Azrieli Group",
      type: "foreign",
      cluster: "tech",
      desc: "Israelsk eigedomsselskap. Kjøpte Green Mountain (største norske datasenter) for $850M.",
      connections: ["green-mountain"],
    },
  ],
}
